# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NinjaLang < Formula
  desc "Ninja Programming Language Binary"
  homepage "https://ninja.jonathan.pt/"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gravataLonga/ninja/releases/download/v0.2.1/ninja-lang_darwin_arm64.tar.gz"
      sha256 "d285396a7a89ac585c1837f4b3dcaf9511509f3721b69c99fe7c113bf2df5537"

      def install
        bin.install "ninja-lang"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gravataLonga/ninja/releases/download/v0.2.1/ninja-lang_darwin_amd64.tar.gz"
      sha256 "f497ee765b66eca7e146b664031439dc135bc7d46f919f225f6e1d898c5bcefe"

      def install
        bin.install "ninja-lang"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gravataLonga/ninja/releases/download/v0.2.1/ninja-lang_linux_amd64.tar.gz"
      sha256 "22e68ae0db4add0534b7bc18dcb8d56ee68d04852bab795d7402551f821f0edc"

      def install
        bin.install "ninja-lang"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gravataLonga/ninja/releases/download/v0.2.1/ninja-lang_linux_arm64.tar.gz"
      sha256 "e44b8bd619d330a555eb969500ea3db4f2ccfce5b097436fb86351bee87b79e9"

      def install
        bin.install "ninja-lang"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gravataLonga/ninja/releases/download/v0.2.1/ninja-lang_linux_arm.tar.gz"
      sha256 "5ef749d539dc201e5ef1eb7e80c2e313eb30d4c1c701f9fabc97b3a7205716fb"

      def install
        bin.install "ninja-lang"
      end
    end
  end
end
