# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NinjaLang < Formula
  desc "Ninja Programming Language Binary"
  homepage "https://ninja.jonathan.pt/"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gravataLonga/ninja/releases/download/v0.2.2/ninja-lang_darwin_amd64.tar.gz"
      sha256 "1f0e58365ef8e224e7a89840d0fd6da82026e57c3a79b43f7d2a94d061533668"

      def install
        bin.install "ninja-lang"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gravataLonga/ninja/releases/download/v0.2.2/ninja-lang_darwin_arm64.tar.gz"
      sha256 "8ed89f77a3007cf025c0b4a52d11a1a7a09d90d604427d8ec5cd1f8709fe0201"

      def install
        bin.install "ninja-lang"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gravataLonga/ninja/releases/download/v0.2.2/ninja-lang_linux_amd64.tar.gz"
      sha256 "727f52a1be6ba52f1703a6f803644cb9f78830beb0dbe893138e6469d1dd71c1"

      def install
        bin.install "ninja-lang"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gravataLonga/ninja/releases/download/v0.2.2/ninja-lang_linux_arm.tar.gz"
      sha256 "15ce64a52eea8198297c4e421008e7af57f166719994bf4d0f0db6199f436ce4"

      def install
        bin.install "ninja-lang"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gravataLonga/ninja/releases/download/v0.2.2/ninja-lang_linux_arm64.tar.gz"
      sha256 "7fc1c433053e3f254ef1548a1e5bf0c1dd515e188ff43c8a03ad2d5fed9fda8b"

      def install
        bin.install "ninja-lang"
      end
    end
  end
end
